### ISSUE TITLE
How to setup input with 3rd person sample project

### ISSUE THREAD

**Issue by narrowengineer** [IDI-Systems/UnrealImGui#12]
I created a simple actor to open an ImGui UI with a couple text fields and a button.  If I enable input in begin play and set shared mouse and shared keyboard to true.  It works for a while but then something happens and all ImGui windows stop responding while the game control continues to work.  Breakpoints in MouseDown are no longer being triggered.

I have not been able to determine how its getting into this state.  I just enter some text in a text box wsad to see if player moves.  Then click somewhere outside ImGui window and repeat key presses wsad.  Player moves accordingly and no text appears in ImGui control.

Keep repeating this and it breaks ImGui windows.

**Comment by SlackingVeteran** [comment]
imgui window needs to be in focus for it to enter text on window text box. You cant click back into game and still have input shared to imgui window
