### ISSUE TITLE
Supporting Unreal Engine 5.4？

### ISSUE THREAD

**Issue by dejavuzzz** [IDI-Systems/UnrealImGui#29]
Will you consider supporting version 5.4 of Unreal Engine in the future?

**Comment by jonpas** [comment]
It should just work as it is, however I have not tested it yet. Let me know if you do! :)

**Comment by NEdhof** [comment]
Yep, it works without any changes.

**Comment by jonpas** [comment]
I will update the README along with updating it to latest imgui, thanks!

**Comment by 2wol** [comment]
Hey!
On Unreal Engine 5.4.2 I get this errors in VS22 when I try to recompile project:
```
Severity	Code	Description	Project	File	Line	Suppression State	Details
Error	C4756	overflow in constant arithmetic	AMBUSH	C:\Users\hesam\Documents\Unreal Projects\AMBUSH\Plugins\UnrealImGui\Source\ThirdParty\ImPlotLibrary\Private\implot_demo.cpp on Lines: 347, 348, 349	


```

Any fix for this?

**Comment by jonpas** [comment]
imgui updated to 1.90.9 on `master` and my test builds succeeded.

Please open a new issue with more details @2wol, however I suspect it is something in your project.
