### ISSUE TITLE
Unable to Access Modifier Keys

### ISSUE THREAD

**Issue by kushagra10025** [IDI-Systems/UnrealImGui#3]
Hi,
I had setup the Plugin perfectly alright and it's working like a charm on **UE5.2**. Thanks for the Fork :)

Although when I am using **Sliders**, I am facing a bug - Unable to edit the value manually which should happen naturally after **Ctrl + Clicking** on the Slider. I also tried the Demo Imgui and check the Input section, none of the Modifier Keys - **Ctrl / Shift / Alt** is working. A Fix or Workaround for the same will be highly appreciated thanks :)

**Comment by Markyparky56** [comment]
This fork appears to have fixed modifier keys, https://github.com/Cleroth/UnrealImGui/commit/ba954da0b91960a4abb890df2eabb24798aa3590

**Comment by jonpas** [comment]
I do not like that it changes ImGui code itself.

**Comment by kushagra10025** [comment]
@Markyparky56 and @jonpas Even I had a similar fix for it. But again it was changing the ImGui Code itself, so I had dropped that. Do you have any other fix in mind? Thanks for your resopnse.

**Comment by SlackingVeteran** [comment]
This should be resolved by #18

**Comment by kushagra10025** [comment]
It seems it has been resolved thanks @SlackingVeteran.
Will be closing this issue, and if I face this again, will create a new one. Thanks :D
