### ISSUE TITLE
Compile Error - "overflow in constant arithmetic"

### ISSUE THREAD

**Issue by 2wol** [IDI-Systems/UnrealImGui#32]
Hey,

So, in issue #29 I wrote that I cannot compile the project correctly after adding UnrealImGui to a project created in Unreal Engine 5.4.2.

I'm still getting errors releated to ImPlot "overflow in constant arithmetic"

Steps to reproduce:
- Create new C++ "First Person Template" Project in Unreal Engine 5.4.2
- Open Project
- Close Project
- Add UnrealImGui into [Project Name]/Plugins/ImGui
- Open Project (I can't cuz I get error that ImGui needs to be recompiled, and compilation results with errors)
- Try To Build Manually (Doesn't work either)

Here is video showing what I'm doing step by step:
https://www.youtube.com/watch?v=JSbJqWXOcik

**Comment by 2wol** [comment]
I did some "research" on the Internet - the problem seems to be in the `INFINITY ` variable, which is used in those lines of code where the error occurs:

```
ImPlot::PlotShaded("Stock 1", xs1, ys1, 101, shade_mode == 0 ? -INFINITY : shade_mode == 1 ? INFINITY : fill_ref, flags);
ImPlot::PlotShaded("Stock 2", xs1, ys2, 101, shade_mode == 0 ? -INFINITY : shade_mode == 1 ? INFINITY : fill_ref, flags);
ImPlot::PlotShaded("Stock 3", xs1, ys3, 101, shade_mode == 0 ? -INFINITY : shade_mode == 1 ? INFINITY : fill_ref, flags);
```

Unfortunately, I am not able to find a solution for this other than removing these three lines of code.... After removing these three lines - project builds correctly and I can use ImGui (also, in `docking` branch I get these errors too, and when I remove them, project also builds correctly.)

**Comment by MifikTTV** [comment]
how did you set the environment variable to Microsoft.NET.Sdk ?

**Comment by 2wol** [comment]
I belive you only need to add `C:\ProgramFiles\dotnet`. 
Some time ago I reinstalled Windows and reconfigured UE with Visual Studio and I have this variable in 'Environment Variables' and I'm not sure if that's it, but I'm guessing 90% on that bcs C++ in UE5 works correctly (except the Issue I described).

Could you let me know if everything is working properly for you? To me it doesn't work properly on UE 5.4.3.

**Comment by divmgl** [comment]
For anyone running into this now: replace `INFINITY` with `std::numeric_limits<float>::infinity()` in the code and it'll compile. Answer grabbed from here: https://forums.unrealengine.com/t/getting-error-c4756-overflow-in-constant-arithmetic-while-building-unreal-5-4-2-from-source-code/1897276/8?u=espaghetters

**Comment by jonpas** [comment]
This is an upstream issue with https://github.com/epezent/implot. Please open an issue there and we will pull the fix in. I would like to avoid doing fixes to upstream projects directly in this project as it is hard to track and not the place for it. Thank you all!
