### ISSUE TITLE
Docking Branch

### ISSUE THREAD

**Issue by SlackingVeteran** [IDI-Systems/UnrealImGui#7]
Could we create a Docking branch for this plugin that include imgui library from docking branch https://github.com/ocornut/imgui/tree/docking

I have a local copy with just the imgui library replaced and it works perfectly. I have been able to use docking without having to change any plugin code at all.

I have a separate debug manager in game that is responsible for creating and managing the imgui windows and is also responsible for enabling/disabling the docking based on if any windows are currently enabled and it works perfectly!

imgui windows are created with FImGuiDelegates::OnWorldDebug delegate and dockspace for docking is created/enabled with FImGuiDelegates::OnWorldEarlyDebug.

Not making any changes to this plugin except for bundling the docking branch allows one to create their own dockspace per their liking. For example I prefer having a menu on the dockspace from where I can access all debug menus. Other may prefer no menu bar at all.

Would really appreciate if a docking branch was created for the plugin instead of someone creating yet another fork of the plugin just for that.

**Comment by jonpas** [comment]
I see no reason not to. https://github.com/IDI-Systems/UnrealImGui/tree/docking here it is, would you mind opening a pull request to do everything relevant for docking towards that branch?

**Comment by SlackingVeteran** [comment]
Created the PR, thank you so much for creating the branch so quickly

**Comment by jonpas** [comment]
Done in https://github.com/IDI-Systems/UnrealImGui/tree/docking, thanks @SlackingVeteran!
